#!/usr/bin/env bash

SEDCMD='s/\\citation{\(.*\)}/\1/p'
KEYPAT='^[0-9]\{4\}[A-Za-z][&.0-9A-Za-z]\{12\}[0-9][A-Z]$'

if [ $# -ne 1 ]; then
	echo "usage: $0 <doc.aux>"
	exit 0
fi

NAME=${1%.aux}
ADSKEY=${ADSKEY:-$(head -n1 ~/.adsbibrc)}

sed -n "${SEDCMD}" "${NAME}.aux" | tr ',' '\n' | sort | uniq > "${NAME}.tmp"
if [ -f ${NAME}.map ]; then
	for key in $(grep -v "${KEYPAT}" "${NAME}.tmp"); do
		grep "^${key}\t" "${NAME}.map" | cut -f 2
	done > "${NAME}.tmp2"
	KEYS=$(grep -h "${KEYPAT}" "${NAME}.tmp" "${NAME}.tmp2" | sort | uniq | sed 's/^\(.*\)$/"\1"/')
else
	KEYS=$(grep "${KEYPAT}" "${NAME}.tmp" | sed 's/^\(.*\)$/"\1"/')
fi
rm -f "${NAME}.tmp" "${NAME}.tmp2"

KEYS=$(echo $KEYS | tr ' ' ',')
curl	-H "Authorization: Bearer:${ADSKEY}"                 \
	-H 'Content-Type: application/json'                  \
	   'https://api.adsabs.harvard.edu/v1/export/bibtex' \
	-X POST                                              \
	-d "{\"bibcode\": [${KEYS}]}"                       |\
jq -r '.export' > "${NAME}.bib"
